esphome:
  name: ducobox
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Ducobox Fallback"
    password: !secret esphome_fallback_password

captive_portal:
logger:
api:
ota:

# text_sensor:
#   - platform: custom
#     lambda: |-
#       int id[4] = {0x00, 0x02, 0x4e, 0x26};
#       auto ducitho = new DucIthoComponent("duco", 6, id);
#       App.register_component(ducitho);
#       return {ducitho->sensor_speed, ducitho->sensor_timer, ducitho->sensor_percentage};
#     text_sensors:
#       - name: ducobox_speed
#         icon: mdi:speedometer
#       - name: ducobox_timer
#         icon: mdi:timer-sand
#       - name: ducobox_percentage
#         icon: mdi:percent

external_components:
  - source: components

fan:
  - platform: duco
    name: Ducobox
